---
- name: Update workstations
  hosts: all
  become: true
  roles:
  - base

- name: Install Elastic Stack
  hosts: all
  become: true
  roles:
  - elasticsearch

- name: Install Kibana                                               
  hosts: all                   
  become: true
  roles:
  - kibana

- name: Install logstash
  hosts: all
  become: true
  roles:
  - logstash

- name: Install Nagios
  hosts: Ubuntu
  become: true
  roles:
  - nagios

- name: Install Prometheus (Ubuntu)
  hosts: Ubuntu
  become: true
  roles:
  - prometheus
